src/VitrineBundle/Form/RegistrationType.php
<?php

namespace VitrineBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class RegistrationType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {
//        parent::buildForm($builder, $options);
        $builder
            ->add('firstName', TextType::class, array())
            ->add('lastName', TextType::class, array())
            ->add('address', TextType::class, array())
            ->add('country', CountryType::class, array())
            ->add('gender', ChoiceType::class, array(
                'label_attr' => array('class' => 'form-check form-check-inline'),
                'attr'       => array('class' => 'form-check-input'),
                'label' => false,
                'choice_translation_domain' => 'messages',
                'choices' => array(
                    'male' => 'male',
                    'female' => 'female',
                ),
            ));
    }

    public function getParent() {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';
    }

    public function getBlockPrefix() {
        return 'app_user_registration';
    }

    public function getName() {
        return $this->getBlockPrefix();
    }

}

src/VitrineBundle/Resources/views/Template/addBeer.html.twig
{% extends 'VitrineBundle:Default:layout.html.twig' %}
{% block navbar %}
    {{ parent() }}
{% include 'VitrineBundle:Default:cover.html.twig' %}
{% endblock %}
{% block content %}

    <div class="marginCover"></div>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <article class="card-body">
                    <h1> Ajout d'une bière</h1>
                    <form action="{{ path('addBeer') }}" method="POST" enctype="multipart/form-data">
                        <div class="form-row">
                            <div class="col form-group">
                                <label> {{ form_label(form.name) }} </label>
                                {{ form_widget (form.name, { 'attr': {'class': 'form-control'} }) }}
                            </div>
                            <div class="col form-group">
                                <label>{{ form_label(form.price) }}</label>
                                {{ form_widget (form.price, { 'attr': {'class': 'form-control'} }) }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label>{{ form_label(form.description) }}</label>
                            {{ form_widget (form.description, { 'attr': {'class': 'form-control'} }) }}
                        </div>
                        <div class="form-group">
                            <label>{{ form_label(form.quantity) }}</label>
                            {{ form_widget (form.quantity, { 'attr': {'class': 'form-control'} }) }}
                        </div>
                        <div class="form-group">
                            {{ form_label (form.image) }}
                            {{ form_widget (form.image, { 'attr': {'class': 'form-control'} }) }}
                        </div>
                        <div class="form-group">
                            {{ form_label (form.alcoholLevel) }}
                            {{ form_widget (form.alcoholLevel, { 'attr': {'class': 'form-control'} }) }}
                        </div>
                        <div class="form-group">
                            {{ form_label (form.type) }}
                            {{ form_widget (form.type, { 'attr': {'class': 'form-control'} }) }}
                        </div>
                        <div class="form-group">
                            {{ form_label (form.category) }}
                            {{ form_widget (form.category, { 'attr': {'class': 'form-control'} }) }}
                        </div>
                        {{ form_rest(form) }}
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block"> Enregistrer </button>
                        </div>


                    </form>
                </article>
            </div>
        </div>
    </div>
{% endblock %}

src/VitrineBundle/Resources/views/Template/addCategory.html.twig
{% extends 'VitrineBundle:Default:layout.html.twig' %}
{% block navbar %}
    {{ parent() }}
{% include 'VitrineBundle:Default:cover.html.twig' %}
{% endblock %}
{% block content %}
    <div class="marginCover"></div>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <article class="card-body">
                    <h1> Ajout d'une catégorie</h1>
                    <form action="{{ path('addCategory') }}" method="POST">
                        <div class="form-group">
                            <label>{{ form_label(form.name) }}</label>
                            {{ form_widget (form.name, { 'attr': {'class': 'form-control'} }) }}
                        </div>
                        {{ form_rest(form) }}
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block"> Enregistrer </button>
                        </div>


                    </form>
                </article>
            </div>
        </div>
    </div>
{% endblock %}

src/VitrineBundle/Resources/views/Template/category.html.twig
{% extends 'VitrineBundle:Default:layout.html.twig' %}
{% block navbar %}
    {{ parent() }}
{% include 'VitrineBundle:Default:cover.html.twig' %}
{% endblock %}
{% block content %}
    <div class="marginCover">
        <nav class="navbar navbar-expand-md bg-dark">
            <div class="container">
                <div class="collapse navbar-collapse justify-content-center" id="navbar2SupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{{ path('category') }}"> {{ 'Reset filtres'|trans }}</a>
                        </li>
                        {% for category in categories %}
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{{ path('category', {'categoryId':category.getId()}) }}"> {{ category.getName() }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </nav>
        <br>
    </div>

    <div class="container">
        <div class="row">
            {% for beer in beers %}
                <div class="col-md-3 col-sm-6">
                    <div class="product-grid">
                        <div class="product-image">
                            <a href="#">
                                {% set path = 'bundles/vitrine/images/'~beer.getCategory().getName()~'/'~beer.getImage() %}
                                <img class="pic-1" src="{{ asset(path)}}" style="height: 120px; width: auto;">
                            </a>
                            <ul class="social">
                                <li><a href="{{ path('productDetails', {'productId':beer.getId()}) }}" data-tip="voir détails"><i class="fa fa-search"></i></a></li>
                                {% if is_granted('ROLE_ADMIN') %}
                                    <li><a href="{{ path('removeBeer', {'beerId':beer.getId()}) }}" data-tip="supprimer"><i class="fas fa-trash"></i></a></li>
                                {% else %}
                                    <li><a href="{{ path('ajoutArticle', {'id':beer.getId(),'quantity':1}) }}" data-tip="ajouter au panier"><i class="fa fa-shopping-cart"></i></a></li>
                                {% endif %}
                            </ul>
                            <span class="product-new-label">Sale</span>
                            <span class="product-discount-label">20%</span>
                        </div>
                        <ul class="rating">
                            <li class="fa fa-star"></li>
                            <li class="fa fa-star"></li>
                            <li class="fa fa-star"></li>
                            <li class="fa fa-star"></li>
                            <li class="fa fa-star disable"></li>
                        </ul>
                        <div class="product-content">
                            <h3 class="title"><a href="#">{{ beer.getName() }}</a></h3>
                            <div class="price">{{ beer.getPrice() }}€
                                <span>{{ beer.getPrice()*1.2 }}€</span>
                            </div>
                            <a class="add-to-cart" href="{{ path('ajoutArticle', {'id':beer.getId(),'quantity':1}) }}">+ ajouter au panier</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    {#<table>#}
    {#{% for beer in beers %}#}
        {#<th> {{ beer.getName() }} </th>#}
        {#<tr>#}
            {#<td>#}
                {#{{ beer.getPrice() }}#}
            {#</td>#}
            {#<td>#}
                {#{{ beer.getDescription() }}#}
            {#</td>#}
            {#<td>#}
                {#{{ beer.getAlcoholLevel() }}#}
            {#</td>#}
            {#<td>#}
                {#{{ beer.getType() }}#}
            {#</td>#}
        {#</tr>#}
    {#{% endfor %}#}
    {#</table>#}
{% endblock %}

src/VitrineBundle/Resources/views/Template/contenuCommand.html.twig
{% extends 'VitrineBundle:Default:layout.html.twig' %}
{% block navbar %}
    {{ parent() }}
{% include 'VitrineBundle:Default:cover.html.twig' %}
{% endblock %}
{% block content %}
    <div class="marginCover"></div>

    {%  if command != null %}
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <h4> Commande n° </h4>
                </div>
                <div class="col-md-4">
                    <h4> Date de la commande. </h4>
                </div>
                <div class="col-md-3">
                    <h4> État de la commande </h4>
                </div>
                <div class="col-md-2">
                    <h4> prix total </h4>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <p> {{ command.getId() }} </p>
                </div>
                <div class="col-md-4">
                    <p> {{ command.getDate()|date('d-m-Y') }} </p>
                </div>
                <div class="col-md-3">
                    <p>
                        {% if command.isValidate() == 0 %}
                            En attente de validation
                        {% else %}
                            Validée
                        {% endif %}
                    </p>
                </div>
                <div class="col-md-2">
                    <p> {{ totalPrice }} </p>
                </div>
            </div>
            <br><br><br>
            <div class="row">
                <div class="col-md-12">
                    <h4> Détails de la commande </h4>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-1">
                    <h5> {{ 'Nom'|trans }} </h5>
                </div>
                <div class="col-md-3">
                    <h5> {{ 'Description'|trans }} </h5>
                </div>
                <div class="col-md-2">
                    <h5> {{ 'quantité'|trans }} </h5>
                </div>
                <div class="col-md-1">
                    <h5> {{ 'prix'|trans }} </h5>
                </div>
            </div>

            {% for commandLine in command.getCommandLines() %}
                {% set beer = commandLine.getProduct() %}
                <hr>
            <div class="row">
                <div class="col-md-2">
                    {% set path = 'bundles/vitrine/images/'~beer.getCategory().getName()~'/'~beer.getImage() %}
                    <img class="pic-1" src="{{ asset(path)}}" style="height: 80px; width: auto;">
                </div>
                <div class="col-md-1"> {{ beer.getName() }} </div>
                <div class="col-md-3" id="description">
                    {% if (beer.getDescription())|length > 150 %}
                        {{ beer.getDescription()|slice(0,150) }}...
                    {% else %}
                        {{ beer.getDescription() }}
                    {% endif %}
                </div>
                <div class="col-md-2"> {{ commandLine.getQuantity() }} </div>
                <div class="col-md-1"> {{ commandLine.getPrice() }} </div>
            </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

src/VitrineBundle/Resources/views/Template/contenuPanier.html.twig
{% extends 'VitrineBundle:Default:layout.html.twig' %}
{% block navbar %}
    {{ parent() }}
{% include 'VitrineBundle:Default:cover.html.twig' %}
{% endblock %}
{% block content %}
    <div class="marginCover"></div>
    {% if contenuPanier|length == 0 %}
        <p> Pas de produit dans le panier.</p>
    {% else %}
        <div class="container">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-1">
                    <h4> {{ 'Nom'|trans }} </h4>
                </div>
                <div class="col-md-3">
                    <h4> {{ 'Description'|trans }} </h4>
                </div>
                <div class="col-md-3">
                    <h4> {{ 'quantité'|trans }} </h4>
                </div>
                <div class="col-md-1">
                    <h4> {{ 'prix'|trans }} </h4>
                </div>
                <div class="col-md-1">
                    <h4> {{ 'sous-total'|trans }} </h4>
                </div>
            </div>

            {% for product in contenuPanier %}
                {% set beer = product[0] %}
                {% set quantity = product[1] %}
                <hr>
                <div class="row">
                    <div class="col-md-2">
                        {% set path = 'bundles/vitrine/images/'~beer.getCategory().getName()~'/'~beer.getImage() %}
                        <img class="pic-1" src="{{ asset(path)}}" style="height: 80px; width: auto;">
                    </div>
                    <div class="col-md-1"> {{ beer.getName() }} </div>
                    <div class="col-md-3" id="description">
                        {% if (beer.getDescription())|length > 150 %}
                            {{ beer.getDescription()|slice(0,150) }}...
                        {% else %}
                            {{ beer.getDescription() }}
                        {% endif %}
                    </div>

                    <div class="col-md-3">
                        <a href="{{ path('ajoutArticle', {'id':beer.getId(), 'quantity':-1}) }}"> <i class="fas fa-minus"></i> </a>
                        {{ quantity }}
                        <a href="{{ path('ajoutArticle', {'id':beer.getId()}) }}"> <i class="fas fa-plus"></i> </a>
                    </div>
                    <div class="col-md-1"> {{ beer.getPrice() }}€/u </div>
                    <div class="col-md-1"> {{ beer.getPrice() * quantity }}€ </div>
                    <div class="col-md-1">
                        <a href="{{ path('removeArticle', {'id':beer.getId()}) }}" data-tip="supprimer"><i class="fas fa-trash"></i></a>
                    </div>
                </div>
            {% endfor %}

            <hr>
            <div class="row">
                <div class="col-md-1">
                    <h4> {{ 'Total'|trans }} </h4>
                </div>
                <div class="col-md-10"></div>
                <div class="col-md-1"> <h4> {{ totalPrice }}€ </h4> </div>
            </div>
            <br><br>
            <div class="row">
                <a href="{{ path('validateCart', {'totalPrice':totalPrice}) }}" class="btn btn-primary btn-block"> {{ 'Valider le panier'|trans }}</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

src/VitrineBundle/Resources/views/Template/index.html.twig
{% extends 'VitrineBundle:Default:layout.html.twig' %}
{% block navbar %}
    {{ parent() }}
{% include 'VitrineBundle:Default:coverIndex.html.twig' %}
{% endblock %}
{% block content %}
    <div class="marginCover"></div>
    <p class="-file-text"> Bienvenue sur notre site d'e-commerce de type qualitatif. </p>

    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse enim nulla, eleifend nec orci ac, tempus laoreet nunc. Nam in dignissim ipsum, eu viverra nisl. Phasellus et ex nibh. Morbi quis dui at turpis condimentum venenatis. Donec luctus justo et laoreet tristique. Aenean sed laoreet sapien. Etiam lorem dui, gravida non ante eget, mattis auctor metus. Fusce auctor iaculis enim, ac porta odio posuere in. Pellentesque volutpat dui id est ultricies semper. Etiam sit amet consectetur sapien, id cursus nulla. Morbi massa nisl, lobortis in viverra et, molestie sit amet ligula. Nulla vulputate lacus massa, sit amet viverra leo volutpat quis. Duis posuere rhoncus eros sit amet accumsan. Proin sed quam et dolor suscipit dapibus a id elit.
    </p>
    <p>
        Aliquam erat volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut at porttitor turpis, eu consectetur neque. Donec non ligula volutpat, semper leo eget, eleifend turpis. Donec ut augue efficitur, finibus tortor nec, pretium odio. Pellentesque est mauris, elementum non ipsum et, viverra iaculis turpis. In tempus ipsum urna, non consequat purus consectetur viverra. Proin tincidunt eu urna at imperdiet. Duis placerat tristique ante nec porta. Ut lobortis mi quis nisi pharetra, ut vestibulum neque pharetra. Morbi sem odio, auctor vitae semper ac, efficitur vel tortor. Nunc finibus justo sit amet tellus elementum tincidunt. Suspendisse vel mi ut felis pretium facilisis at sed justo.
    </p>
    <p>
        Aliquam nec ante nec diam porta porta et vitae nunc. Nam nec augue iaculis, convallis quam id, porta sem. Ut tempor leo sed massa placerat, at imperdiet nulla posuere. Vestibulum congue ligula faucibus nisi interdum tristique. Suspendisse nibh ligula, dapibus in tellus vitae, dictum tempor leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce fringilla pretium dui, mollis imperdiet urna rhoncus a. Morbi finibus sed erat non lacinia. Sed gravida posuere felis, id lobortis lacus pulvinar et. Curabitur sit amet diam eget elit volutpat tempus et vitae dolor. In in elit turpis. Morbi efficitur, ex et tempor imperdiet, risus nisi porttitor augue, interdum consequat purus leo sit amet lorem.
    </p>
    <p>
        Donec ut ipsum vitae magna placerat aliquet. Curabitur pretium auctor ex at tempus. In hac habitasse platea dictumst. Duis vitae fringilla orci, sed condimentum nisl. Curabitur mollis mollis dolor at rutrum. Duis elit ante, rutrum varius fermentum ac, scelerisque interdum risus. Duis ullamcorper quam lorem, sed fermentum ex blandit quis. Integer lacinia ex eu enim posuere tempus. Pellentesque ac nunc tortor. Sed sagittis varius ex et tincidunt. Nam ac bibendum lacus. Nulla tincidunt interdum orci in tempor.
    </p>
{% endblock %}

src/VitrineBundle/Resources/views/Template/productDetails.html.twig
{% extends 'VitrineBundle:Default:layout.html.twig' %}
{% block navbar %}
    {{ parent() }}
{% include 'VitrineBundle:Default:cover.html.twig' %}
{% endblock %}
{% block content %}
    <div class="marginCover"></div>

    <div class="row">
        <div class="col-md-4 mr-auto order-2 order-md-1">
            {% set path = 'bundles/vitrine/images/'~beer.getCategory().getName()~'/'~beer.getImage() %}
            <img src="{{ asset(path)}}" style="height: 400px; width: auto;">
        </div>
        <div class="px-md-5 p-3 d-flex flex-column align-items-start justify-content-center col-md-7 order-1 order-md-2">
            <h1>{{ beer.getName() }}</h1>
            <h5> {{ 'Prix'|trans }} : {{ beer.getPrice() }}€</h5>
            <p class="mb-3 lead">
                {{ beer.getDescription() }}
            </p>
            <p class="mb-3 lead">
                Quantité en stock : {{ beer.getQuantity() }}
            </p>
            <div class="row text-muted">
                <form action="{{ path('ajoutArticle', {'id':beer.getId()}) }}" method="POST">
                    <div>
                        <label for="">
                            {{ 'Quantité'|trans }} :
                            <input type="number" name="quantity" class="form-control" value="1">
                        </label>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-danger">+ {{ 'Ajouter au panier'|trans }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/VitrineBundle/Resources/views/Template/products.html.twig
{% extends 'VitrineBundle:Default:layout.html.twig' %}
{% block navbar %}
    {{ parent() }}
{% include 'VitrineBundle:Default:cover.html.twig' %}
{% endblock %}
{% block content %}
    <div class="marginCover"></div>

    <h3> Les 2 bières les plus vendues !</h3>
    <div class="container">
        <div class="row">
        {% for beer in mostSaleBeers %}
            <div class="col-md-3 col-sm-6">
                <div class="product-grid">
                    <div class="product-image">
                        <a href="#">
                            {% set path = 'bundles/vitrine/images/'~beer.getCategory().getName()~'/'~beer.getImage() %}
                            <img class="pic-1" src="{{ asset(path)}}" style="height: 120px; width: auto;">
                        </a>
                        <ul class="social">
                            <li><a href="{{ path('productDetails', {'productId':beer.getId()}) }}" data-tip="voir détails"><i class="fa fa-search"></i></a></li>
                            {% if is_granted('ROLE_ADMIN') %}
                                <li><a href="{{ path('removeBeer', {'beerId':beer.getId()}) }}" data-tip="supprimer"><i class="fas fa-trash"></i></a></li>
                            {% else %}
                                <li><a href="{{ path('ajoutArticle', {'id':beer.getId(),'quantity':1}) }}" data-tip="ajouter au panier"><i class="fa fa-shopping-cart"></i></a></li>
                            {% endif %}
                        </ul>
                        <span class="product-new-label">Sale</span>
                        <span class="product-discount-label">20%</span>
                    </div>
                    <ul class="rating">
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star"></li>
                        <li class="fa fa-star disable"></li>
                    </ul>
                    <div class="product-content">
                        <h3 class="title"><a href="#">{{ beer.getName() }}</a></h3>
                        <div class="price">{{ beer.getPrice() }}€
                            <span>{{ beer.getPrice()*1.2 }}€</span>
                        </div>
                        <a class="add-to-cart" href="{{ path('ajoutArticle', {'id':beer.getId(),'quantity':1}) }}">+ ajouter au panier</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>

    <hr><hr>

    <div class="container">
        <div class="row">
            {% for beer in beers %}
                <div class="col-md-3 col-sm-6">
                    <div class="product-grid">
                        <div class="product-image">
                            <a href="#">
                                {% set path = 'bundles/vitrine/images/'~beer.getCategory().getName()~'/'~beer.getImage() %}
                                <img class="pic-1" src="{{ asset(path)}}" style="height: 120px; width: auto;">
                            </a>
                            <ul class="social">
                                <li><a href="{{ path('productDetails', {'productId':beer.getId()}) }}" data-tip="voir détails"><i class="fa fa-search"></i></a></li>
                                {% if is_granted('ROLE_ADMIN') %}
                                    <li><a href="{{ path('removeBeer', {'beerId':beer.getId()}) }}" data-tip="supprimer"><i class="fas fa-trash"></i></a></li>
                                {% else %}
                                    <li><a href="{{ path('ajoutArticle', {'id':beer.getId(),'quantity':1}) }}" data-tip="ajouter au panier"><i class="fa fa-shopping-cart"></i></a></li>
                                {% endif %}
                            </ul>
                            <span class="product-new-label">Sale</span>
                            <span class="product-discount-label">20%</span>
                        </div>
                        <ul class="rating">
                            <li class="fa fa-star"></li>
                            <li class="fa fa-star"></li>
                            <li class="fa fa-star"></li>
                            <li class="fa fa-star"></li>
                            <li class="fa fa-star disable"></li>
                        </ul>
                        <div class="product-content">
                            <h3 class="title"><a href="#">{{ beer.getName() }}</a></h3>
                            <div class="price">{{ beer.getPrice() }}€
                                <span>{{ beer.getPrice()*1.2 }}€</span>
                            </div>
                            <a class="add-to-cart" href="{{ path('ajoutArticle', {'id':beer.getId(),'quantity':1}) }}">+ ajouter au panier</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/VitrineBundle/Resources/views/Template/viewCommands.html.twig
{% extends 'VitrineBundle:Default:layout.html.twig' %}
{% block navbar %}
    {{ parent() }}
{% include 'VitrineBundle:Default:cover.html.twig' %}
{% endblock %}
{% block content %}
    {% if is_granted('ROLE_ADMIN') == false %}
    <div class="marginCover">
        <nav class="navbar navbar-expand-md bg-dark">
            <div class="container">
                <div class="collapse navbar-collapse justify-content-center" id="navbar2SupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{{ path('commands') }}"> {{ 'Commandes en cours'|trans }}</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{{ path('validatedCommands') }}"> {{ 'Commandes validées'|trans }}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <br>
    </div>
    {% endif %}

    {% if validate == false %}
        <h3> Les commandes en attente de validation </h3>
    {% else %}
        <h3> Les commandes validées </h3>
    {% endif %}
    <br>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-2"></div>
        <div class="col-md-1"> <h4> {{ 'Nom'|trans }} </h4> </div>
        <div class="col-md-3" id="description"> <h4> {{ 'Description'|trans }} </h4>  </div>
        <div class="col-md-2"> <h4> {{ 'Quantité'|trans }} </h4> </div>
        <div class="col-md-1"> <h4> {{ 'Prix'|trans }} </h4> </div>
    </div>
    {% if commands != null %}
        {% for command in commands %}
            <div class="line"></div>
            <br>
            <h5> Commande n°{{ command.getId() }}
                {% if is_granted('ROLE_ADMIN') %}
                    <a class="" href="{{ path('validCommand', {'commandId':command.getId()}) }}"> {{ 'Je valide'|trans }}</a>
                {% endif %}
            </h5>
            {% for commandLine in command.getCommandLines() %}
                {% set beer = commandLine.getProduct() %}
                <hr>
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-2">
                    {% set path = 'bundles/vitrine/images/'~beer.getCategory().getName()~'/'~beer.getImage() %}
                    <img class="pic-1" src="{{ asset(path)}}" style="height: 80px; width: auto;">
                </div>
                <div class="col-md-1"> {{ beer.getName() }} </div>
                <div class="col-md-3" id="description">
                    {% if (beer.getDescription())|length > 150 %}
                        {{ beer.getDescription()|slice(0,150) }}...
                    {% else %}
                        {{ beer.getDescription() }}
                    {% endif %}
                </div>
                <div class="col-md-2"> {{ commandLine.getQuantity() }} </div>
                <div class="col-md-1"> {{ commandLine.getPrice() }} </div>
            </div>
            {% endfor %}
        {% endfor %}
    {% endif %}
{% endblock %}